# Generated by Django 2.2.11 on 2020-04-21 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaraType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NanoPowder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tara_number', models.IntegerField(default=0, verbose_name='Номер тары')),
                ('brutto_mass', models.FloatField(verbose_name='Масса брутто')),
                ('material', models.CharField(max_length=200, verbose_name='Материал')),
                ('prod_date', models.DateField(null=True, verbose_name='дата получения')),
                ('prod_number', models.IntegerField(null=True, verbose_name='номер пуска')),
                ('pack_date', models.DateField(null=True, verbose_name='дата фасовки')),
                ('poverhn', models.FloatField(null=True, verbose_name='уд.поверхность')),
                ('plotnost', models.FloatField(null=True, verbose_name='нас.плотность')),
                ('label_text', models.TextField(verbose_name='Надпись на этикетке')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Служебное примечание')),
                ('mass_check_date', models.DateField(null=True, verbose_name='Дата проверки массы')),
                ('plotnost_check_date', models.DateField(null=True, verbose_name='Дата пров. уд.плотн')),
                ('netto_mass', models.FloatField(null=True, verbose_name='Масса нетто')),
                ('collect_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CollectPoint', verbose_name='точка сбора')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Location', verbose_name='Местоположение')),
                ('tara_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TaraType', verbose_name='Тип тары')),
            ],
            options={
                'verbose_name': 'Выпуск нанопорошка',
                'verbose_name_plural': 'Выпуски нанопорошка',
            },
        ),
    ]
