# Generated by Django 2.2.11 on 2020-04-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectpoint',
            options={'verbose_name': 'Точка сбора продукции', 'verbose_name_plural': 'Точки сбора продукции'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Место нахождения', 'verbose_name_plural': 'Места нахождения'},
        ),
        migrations.AlterModelOptions(
            name='taratype',
            options={'verbose_name': 'Тип упаковки', 'verbose_name_plural': 'Типы упаковки'},
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='taratype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
